config/routes.rb
Rails.application.routes.draw do
	root 'zadania#index'

	get '/zadania' => 'zadania#index'
	get 'zadania/new' => 'zadania#new'
	post 'zadania' => 'zadania#create'
	get 'zadania/:id' => 'zadania#edit', as: :zadanium
	patch '/zadania/:id' => 'zadania#update'
	delete 'zadania/:id' => 'zadania#destroy'

	get '/projekts' => 'projekts#index'
	get '/projekts/new' => 'projekts#new'
	post 'projekts' => 'projekts#create'
	get 'projekts/:id' => 'projekts#edit', as: :projekt
	patch 'projekts/:id' => 'projekts#update'
	delete 'projekts/:id' => 'projekts#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/projekt.rb
class Projekt < ApplicationRecord
  has_many :zadania
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/zadanium.rb
class Zadanium < ApplicationRecord
  belongs_to :projekt
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
end

app/controllers/projekts_controller.rb
class ProjektsController < ApplicationController

  def index
    @projekts = Projekt.all
  end
  def new
    @projekts = Projekt.new
  end
  def create
    @projekts = Projekt.new(projekt_params)
    if @projekts.save
      redirect_to '/projekts'
    else
      render 'new'
    end
  end

  def edit
    @projekt = Projekt.find(params[:id])
  end
  
  def update
		@projekt = Projekt.find(params[:id])
		if @projekt.update(projekt_params)
			redirect_to '/projekts'
		else
			render 'edit'
		end
	end

	def destroy
		@projekt = Projekt.find(params[:id])
		@projekt.destroy

		redirect_to '/projekts'
	end

  def projekt_params
    params.require(:projekt).permit(:nazwa, :opis, :zadania_id)
  end
end

app/controllers/zadania_controller.rb
class ZadaniaController < ApplicationController

	def index
		@zadania = Zadanium.all
	end

	def show
		@zadanium = Zadanium.find(params[:id])
	end

	def new
		@zadania = Zadanium.new
	end

	def create
		@zadania = Zadanium.new(zadanium_params)
		if @zadania.save
			redirect_to '/zadania'
		else
			render 'new'
		end
	end

	def edit
		@zadanium = Zadanium.find(params[:id])
	end

	def update
		@zadanium = Zadanium.find(params[:id])
		if @zadanium.update(zadanium_params)
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def destroy
		@zadanium = Zadanium.find(params[:id])
		@zadanium.destroy

		redirect_to root_path
	end

	private
	def zadanium_params
		params.require(:zadanium).permit(:nazwa, :termin, :przydzial, :opis)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/helpers/projekts_helper.rb
module ProjektsHelper
end

app/helpers/zadania_helper.rb
module ZadaniaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projekts/edit.html.erb
<% provide(:title, "Edytuj projekt") %>
<h1>Update zadanie</h1>

<div class="row">

		<%= form_for(@projekt) do |f| %>


 			<%= f.label :projekt %>
			<%= f.text_area :nazwa %>

			<%= f.submit "Save changes", class: "btn btn-primary" %>
			<%= link_to 'Usuń', projekt_path(@projekt), method: :delete, data: { confirm: 'Are you sure?' } %>

		<% end %>

</div>

app/views/projekts/index.html.erb
<h1>Projekty</h1>
<% @projekts.each do |p| %>
			<div class="projekt">

  			<p class="content"><%= p.nazwa %></p>
  			<p class="content"><%= p.opis %></p>
  			<p class="content"><%= link_to "Edytuj", projekt_path(@projekt) %>

			</div>
		<% end %>
<%= link_to 'Nowy Projekt', "projekts/new" %>

app/views/projekts/new.html.erb
<h1>Dodaj zadanie</h1>

<%= form_for(@projekts) do |f| %>
  <div class="field">
    <%= f.label :projekt %><br>
    <p>Nazwa projektu:</p><%= f.text_area :nazwa %>
    <p>Opis:</p><%= f.text_area :opis %>
  </div>
  <div class="actions">
    <%= f.submit "Stwórz" %>
  </div>
  <%= link_to 'Wróć', "/projekts" %>
<% end %>

app/views/zadania/edit.html.erb
<% provide(:title, "Edytuj zadanie") %>
<h1>Update zadanie</h1>

<div class="row">
	
		<%= form_for(@zadanium) do |f| %>
			

 			<%= f.label :zadanium %>
			<%= f.text_area :nazwa %>

			<%= f.submit "Save changes", class: "btn btn-primary" %>
			<%= link_to 'Usuń', zadania_path(@zadanium), method: :delete, data: { confirm: 'Are you sure?' } %>

		<% end %>
	
</div>

app/views/zadania/index.html.erb
<h1>Zadania</h1>
<% @zadania.each do |zadanium| %>
			<div class="zadanie">

  			<p class="content"><%= zadanium.nazwa %></p>
  			<p class="content"><%= zadanium.opis %></p>
  			<p class="content"><%= link_to "Edytuj", zadanium_path(zadanium) %>
				<p class="content"><%= link_to "Usuń", zadanium_path(zadanium),
					method: :delete, data: { confirm: 'Are you sure?' } %>

			</div>
		<% end %>
<%= link_to 'Nowe zadanie', "zadania/new" %>

app/views/zadania/new.html.erb
<h1>Dodaj zadanie</h1>

<%= form_for(@zadania) do |f| %>  
  <div class="field"> 
    <%= f.label :zadanium %><br> 
    <p>Nazwa zadania:</p><%= f.text_area :nazwa %> 
    <p>Do kiedy:</p><%= f.text_area :termin %>
    <p>Przydział:</p><%= f.text_area :przydzial %>
    <p>Opis:</p><%= f.text_area :opis %>
  </div> 
  <div class="actions"> 
    <%= f.submit "Stwórz" %> 
  </div> 
  <%= link_to 'Wróć', "/zadania" %>
<% end %> 